import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val animation: String = "androidx.compose.animation:animation:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val foundation: String = "androidx.compose.foundation:foundation:_"

    public const val material3: String = "androidx.compose.material3:material3:_"

    public const val material_icons_extended: String =
            "androidx.compose.material:material-icons-extended:_"

    public const val androidx_compose_runtime_runtime: String = "androidx.compose.runtime:runtime:_"

    public const val ui: String = "androidx.compose.ui:ui:_"

    public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    public const val ui_test_manifest: String = "androidx.compose.ui:ui-test-manifest:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val accompanist_pager: String = "com.google.accompanist:accompanist-pager:_"

    public const val accompanist_systemuicontroller: String =
            "com.google.accompanist:accompanist-systemuicontroller:_"

    public const val play_services_maps: String = "com.google.android.gms:play-services-maps:_"

    public const val secrets_gradle_plugin: String =
            "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:_"

    public const val com_google_devtools_ksp_gradle_plugin: String =
            "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:_"

    public const val symbol_processing: String = "com.google.devtools.ksp:symbol-processing:_"

    public const val maps_compose: String = "com.google.maps.android:maps-compose:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val coil_compose: String = "io.coil-kt:coil-compose:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jetbrains_kotlin_android_gradle_plugin: String =
            "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:_"

    public const val compose_destinations_animations_core: String = "io.github.raamcosta.compose-destinations:animations-core:_"

    public const val compose_destinations_ksp: String = "io.github.raamcosta.compose-destinations:ksp:_"
}
